-- CREATE TABLE IF NOT EXISTS `organizr`.`user` (
--   `id` INT NOT NULL AUTO_INCREMENT,
--   `username` VARCHAR(45) NOT NULL,
--   `password` VARCHAR(45) NOT NULL,
--   `email` VARCHAR(45) NOT NULL,
--   `enabled` TINYINT NOT NULL,
--   PRIMARY KEY (`id`))