version: '3.8'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: parentOrganizr
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    