### Get all pupils
GET http://localhost:8080/pupil

### Get person by id
GET http://localhost:8080/pupil/1

### Create pupil
POST http://localhost:8080/pupil HTTP/1.1
content-type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john@doe.com",
  "phoneNumber": "1234567890",
  "birthdate": "2011-12-03T10:15:30",
  "address": "Some address"
}

### Update pupil by id
PUT http://localhost:8080/pupil/1 HTTP/1.1
content-type: application/json

{
  "firstName": "John",
  "phoneNumber": "1234567890",
  "birthDate": "1990-01-01"
}
