### Get all pupils
GET http://localhost:8080/pupil

### Get person by id
GET http://localhost:8080/pupil/5

### Create pupil
POST http://localhost:8080/pupil HTTP/1.1
content-type: application/json

{
  "firstName": "Freddy",
  "lastName": "Fink",
  "email": "freddy@fink.com",
  "phoneNumber": "988654321",
  "birthdate": "1996-12-03T10:15:30",
  "address": "Some address"
}

### Update pupil by id
PUT http://localhost:8080/pupil/6 HTTP/1.1
content-type: application/json

{
  "id": 3,
  "firstName": "Christian",
  "lastName": "Larson",
  "birthdate": "1990-01-01"
}

### Get all Parents
